INSERT INTO BUILDING (NUMBER_OF_ROOMS)
VALUES (120);

INSERT INTO PICTURE (BUILDING_ID, NAME)
VALUES (1, 'Fat Lady');
INSERT INTO PICTURE (BUILDING_ID, NAME)
VALUES (1, 'Sir Cadogan');
INSERT INTO PICTURE (BUILDING_ID, NAME)
VALUES (1, 'Circe');

INSERT INTO STUDENT(NAME, HOUSE_TYPE, PET_TYPE)
VALUES ('Ronald Bilius Weasley', 'GRYFFINDOR', 'RAT');
INSERT INTO STUDENT(NAME, HOUSE_TYPE, PET_TYPE)
VALUES ('Hermione Granger', 'GRYFFINDOR', 'CAT');
INSERT INTO STUDENT(NAME, HOUSE_TYPE, PET_TYPE)
VALUES ('Harry Potter', 'GRYFFINDOR', 'OWL');
INSERT INTO STUDENT(NAME, HOUSE_TYPE, PET_TYPE)
VALUES ('Draco Malfoy', 'SLYTHERIN', 'NONE');

INSERT INTO ROOM (ROOM_NUMBER, CAPACITY, NUMBER_OF_BEDS, HAS_EMPTY_BEDS, BUILDING_ID)
VALUES (1, 4, 4, true, 1);
INSERT INTO ROOM (ROOM_NUMBER, CAPACITY, NUMBER_OF_BEDS, HAS_EMPTY_BEDS, BUILDING_ID)
VALUES (2, 4, 4, true, 1);
INSERT INTO ROOM (ROOM_NUMBER, CAPACITY, NUMBER_OF_BEDS, HAS_EMPTY_BEDS, BUILDING_ID)
VALUES (3, 4, 4, false, 1);
INSERT INTO ROOM (ROOM_NUMBER, CAPACITY, NUMBER_OF_BEDS, HAS_EMPTY_BEDS, BUILDING_ID)
VALUES (21, 4, 4, true, 1);

INSERT INTO RESIDENT (STUDENT_ID, ROOM_ID)
VALUES (1, 1);
INSERT INTO RESIDENT (STUDENT_ID, ROOM_ID)
VALUES (2, 2);
INSERT INTO RESIDENT (STUDENT_ID, ROOM_ID)
VALUES (3, 1);
INSERT INTO RESIDENT (STUDENT_ID, ROOM_ID)
VALUES (4, 4);

INSERT INTO RECIPE (NAME) VALUES ( 'Amortentia' );
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (1, 'BEZOAR');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (1, 'BOOMSLANG_SKIN');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (1, 'DOXY_EGG');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (1, 'DRAGON_CLAW');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (1, 'FLUXWEED');

INSERT INTO RECIPE (NAME) VALUES ( 'Doxycide' );
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (2, 'DRAGON_CLAW');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (2, 'BOOMSLANG_SKIN');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (2, 'LEECH');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (2, 'DRAGON_CLAW');
INSERT INTO RECIPE_INGREDIENT ( RECIPE_ID, INGREDIENT_NAME ) VALUES (2, 'FLUXWEED');

INSERT INTO STUDENT_RECIPE (STUDENT_ID, RECIPE_ID) VALUES ( 2, 1 );
INSERT INTO STUDENT_RECIPE (STUDENT_ID, RECIPE_ID) VALUES ( 2, 2 );
INSERT INTO STUDENT_RECIPE (STUDENT_ID, RECIPE_ID) VALUES ( 4, 2 );
